# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - name: Lint
        run: npm run lint

  generate:
    if: github.ref == 'refs/heads/main'
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}      
      - name: download   
        env:
          DROPBOX_API_TOKEN: ${{ secrets.DROPBOX_API_TOKEN }}
        run: npm run download      
      - name: generate
        run: npm run generate
      - uses: actions/upload-artifact@v2
        with:
          name: generated-stories
          path: |
            src/stories
  
  build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: generate
    steps:      
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - uses: actions/download-artifact@v2
        with:
          name: generated-stories
      - name: build        
        run: npm run build-storybook
      - uses: actions/upload-artifact@v2
        with:
          name: packaged-storybook
          path: storybook-static
  
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: packaged-storybook
      - name: check
        run: ls -al
      - name: Deploy 🚀                
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: storybook-static # The folder the action should deploy.
